### ISSUE TITLE
Primary key is not "id"

### ISSUE THREAD

**Issue by ryderlee** [feathersjs/feathers-knex#101] opened 2017-04-27 11:20 UTC
I tried to declare the user table as:

```
table.increments('user_id').primary();
table.string('username');
```

but when I do a HTTP GET call to the server `/user/1`
I got the error

```
{
  "name": "BadRequest",
  "message": "select `user`.* from `user` where `id` = '1' - ER_BAD_FIELD_ERROR: Unknown column 'id' in 'where clause'",
  "code": 400,
  "className": "bad-request",
  "errors": {}
}
```

**Expected result**

the user record would be shown accordingly.

**Comment by shadowRR** [comment] 2017-04-27 14:50
On your example, you've basically named the primary key "user_id". If you want a primary key with the "id" field name :
```
table.increments( 'id' ).primary();
```

**Comment by ryderlee** [comment] 2017-04-27 15:40
and I would like to name the primary key as "user_id". The problem is, when I make a HTTP GET call to `/user/1` I got the above error.
Any idea?

**Comment by daffl** [comment] 2017-04-27 15:52
If you want to use an id key that is not `id` you have to tell the adapter which `id` property to use when initializing the service as [documented here](https://docs.feathersjs.com/api/databases/knexjs.html#api).

```
app.use('/messages', service({
  id: 'user_id',
  Model: db,
  name: 'messages'
}));
```

**Comment by ryderlee** [comment] 2017-04-28 08:20
well it works in `find` but not under `get`, so if I am calling `/user/` it works, but not `/user/1` and the error is : 
```
{
  "name": "NotFound",
  "message": "No record found for id '1'",
  "code": 404,
  "className": "not-found",
  "errors": {}
}
```

Any idea?

**Comment by daffl** [comment] 2017-04-28 15:04
Are you sure? This functionality is being explicitly tested [here](https://github.com/feathersjs/feathers-knex/blob/master/test/index.test.js#L42).

**Comment by daffl** [comment] 2017-05-03 07:34
I'm going to close this since setting a different id should be supported as mentioned in the comments and we don't have enough additional information to reproduce the issue.

**Closed by daffl** 2017-05-03 07:34 UTC

**Comment by ryderlee** [comment] 2017-05-05 09:07
Sorry but I still not able to fix it. I would like to highlight the endpoint that I call is to `/user/1` (that means to get the user with user_id = 1) the error I got is :
```
info: error: user - Method: get: No record found for id '1'
error:  Error
```

again the `id` property has been defined and I can do a get by calling `/user` and the result is good.

**Comment by daffl** [comment] 2017-05-09 18:08
Can you share a repository to reproduce the issue?
